blank_issues_enabled: false
contact_links:
  - name: Hackathon Questions or Help
    url: mailto:freddy@directions4partners.com
    about: Send an email if you have any questions about the Directions EMEA 2025 Hackathon.
