name: "Auto-comment on new hackathon ideas"

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add a friendly comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ğŸ‘‹ Hi @${{ github.event.issue.user.login }}!  
            Thanks for submitting your **Directions EMEA 2025 Hackathon idea** ğŸ‰  

            Youâ€™re officially part of the hackathon!  
            - ğŸ•’ Submission received before **October 6th, 15:30** â€” perfect.  
            - ğŸš€ Development runs until **January 5th, 2026**.  
            - ğŸ Final submission is due on **January 6th, 2026**.  
            - ğŸ† The winner will be announced during the **Directions Webinar on January 27th, 2026**.  

            We canâ€™t wait to see what youâ€™ll build. Good luck! ğŸ’¡  
            _â€“ The Directions EMEA 2025 Hackathon Team_
